Refactor case code

diff --git a/linux-ck-autobuild b/linux-ck-autobuild
--- a/linux-ck-autobuild
+++ b/linux-ck-autobuild
@@ -427,21 +427,21 @@ case "$option" in
     n ) new_profile $OPTARG;;
     a ) set_subarches;;
     : ) echo "Option requres an secord argument -- $OPTARG" && exit 1;;
-    ? ) [ -n ${OPTARG} ] && echo "Option not found, try -h or --help" && exit 1;;
+    ? ) [ -n "$OPTARG" ] && { echo "Option not found, try -h or --help" && exit 1; }
+        : > $BUILD_DIR/.last_build
+        for profile in ${PROFILES[@]}; do
+            load_config
+            if [ -r "$CONFIG_DIR/$profile.conf" ]; then
+                . "$CONFIG_DIR/$profile.conf"
+            else
+                echo "Profile $profile not found. Skipping"
+                profile="linux-ck-autobuild"
+            fi
+            echo -e "\n\nProfile loaded: $profile.conf"
+            main_program
+            eval $USER_COMMAND2
+        done
+        update_repo "cleanup"
+        eval $USER_COMMAND3
+        ;;
 esac
-
-: > $BUILD_DIR/.last_build
-for profile in ${PROFILES[@]}; do
-    load_config
-    if [ -r "$CONFIG_DIR/$profile.conf" ]; then
-        . "$CONFIG_DIR/$profile.conf"
-    else
-        echo "Profile $profile not found. Skipping"
-        profile="linux-ck-autobuild"
-    fi
-    echo -e "\n\nProfile loaded: $profile.conf"
-    main_program
-    eval $USER_COMMAND2
-done
-update_repo "cleanup"
-eval $USER_COMMAND3
